# -*- coding: utf-8 -*-
"""Proyecto.1p

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18DOkrckjqLc-gXMkYdlvdEt_7P75dJ6J
"""

!git clone https://github.com/hchocobar/ucu_pad_project_2023_01.git

import re

filename = "../ucu_pad_project_2023_01/data"
file = open(filename)
text = file.read

foo = re.findall(>Popularity in(\d+)</h3>, text)