# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Fx0wwkP1KYfclW5sRS92xESWM8Z30x7
"""

!git clone https://github.com/hchocobar/ucu_pad_practice_2023_01.git

file = open("ucu_pad_practice_2023_01/data/mbox-short.txt")
pattern = "New Revision"
data = []

for line in file:
    line = line.rstrip()
    result = re.findall(pattern, line)
    if result:
      data.append(line)

data, len(data)

data = ['New Revision: 39772', 'New Revision: 39771', 'New Revision: 39770', 'New Revision: 39769', 'New Revision: 39766', 'New Revision: 39765', 'New Revision: 39764', 'New Revision: 39763', 'New Revision: 39762', 'New Revision: 39761', 'New Revision: 39760', 'New Revision: 39759', 'New Revision: 39758', 'New Revision: 39757', 'New Revision: 39756', 'New Revision: 39755', 'New Revision: 39754', 'New Revision: 39753', 'New Revision: 39752', 'New Revision: 39751', 'New Revision: 39750', 'New Revision: 39749', 'New Revision: 39746', 'New Revision: 39745', 'New Revision: 39744', 'New Revision: 39743', 'New Revision: 39742']

# Extraer los números de cada elemento de la lista
revision_numbers = [int(re.search(r'\d+', item).group()) for item in data]

# Calcular el promedio
if revision_numbers:
    promedio = sum(revision_numbers) / len(revision_numbers)
else:
    promedio = 0

# Imprimir el resultado
print("El promedio de los números es:", promedio)

file = open("ucu_pad_practice_2023_01/data/mbox.txt")
pattern = "New Revision"
data = []

for line in file:
    line = line.rstrip()
    result = re.findall(pattern, line)
    if result:
      data.append(line)

data, len(data)

data = [
    'New Revision: 38782', 'New Revision: 38781', 'New Revision: 38780', 'New Revision: 38779',
    'New Revision: 38778', 'New Revision: 38777', 'New Revision: 38776', 'New Revision: 38775',
    'New Revision: 38774', 'New Revision: 38773', 'New Revision: 38697', 'New Revision: 38541',
    'New Revision: 38540', 'New Revision: 38539', 'New Revision: 38538', 'New Revision: 38537',
    'New Revision: 38536', 'New Revision: 38535', 'New Revision: 38534', 'New Revision: 38533',
    'New Revision: 38532', 'New Revision: 38531', 'New Revision: 38530', 'New Revision: 38529',
    'New Revision: 38528', 'New Revision: 38527', 'New Revision: 38526', 'New Revision: 38525',
    'New Revision: 38524', 'New Revision: 38523', 'New Revision: 38521', 'New Revision: 38520',
    'New Revision: 38519', 'New Revision: 38518', 'New Revision: 38517', 'New Revision: 38515',
    'New Revision: 38514', 'New Revision: 38513', 'New Revision: 38512', 'New Revision: 38511',
    'New Revision: 38510', 'New Revision: 38509', 'New Revision: 38508', 'New Revision: 38507',
    'New Revision: 38506', 'New Revision: 38505', 'New Revision: 38504', 'New Revision: 38502',
    'New Revision: 38501', 'New Revision: 38500', 'New Revision: 38499', 'New Revision: 38498',
    'New Revision: 38492', 'New Revision: 38491', 'New Revision: 38490', 'New Revision: 38489', '1790'
]

# Extraer los números de cada elemento de la lista
revision_numbers = [int(re.search(r'\d+', item).group()) for item in data]

# Calcular el promedio
if revision_numbers:
    promedio = sum(revision_numbers) / len(revision_numbers)
else:
    promedio = 0

# Imprimir el resultado
print("El promedio de los números es:", promedio)